name: Build Digital Ink

on:
  push:
    paths:
      - 'android/digitalink/**'
      - '.github/workflows/digitalink.yml'
  pull_request:
    paths:
      - 'android/digitalink/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Change to digitalink directory
        working-directory: android/digitalink
        run: |
          chmod +x ./gradlew
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: digitalink-apk
          path: android/digitalink/app/build/outputs/apk/debug/*.apk
