name: Build Digital Ink

on:
  push:
    paths:
      - 'android/digitalink/**'
      - '.github/workflows/digitalink.yml'
  pull_request:
    paths:
      - 'android/digitalink/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant Gradle permission
        run: chmod +x ./gradlew

      - name: Build Digital Ink only
        run: ./gradlew :android:digitalink:assembleDebug

      - name: List APK output
        run: ls -R android/digitalink/build/outputs/apk/

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: digitalink-debug-apk
          path: android/digitalink/build/outputs/apk/debug/*.apk
