name: Build Digital Ink

on:
  push:
    paths:
      - 'android/digitalink/**'
      - '.github/workflows/digitalink.yml'
  pull_request:
    paths:
      - 'android/digitalink/**'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: android/digitalink

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant Gradle permissions
        run: chmod +x ./gradlew

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: digitalink-debug-apk
          path: android/digitalink/app/build/outputs/apk/debug/app-debug.apk
